version: '3.11'

services:
  xj_qhkxxlz:
    image: 564d64adeb03
    container_name: xj_qhkxxlz
    restart: always
    ports:
      - "5000:5050"
    volumes:
      - E:/hxkj/xinjiang/data:/data
      - E:/hxkj/xinjiang/logs:/logs
      - E:/hxkj/xinjiang/app:/app
      - E:/hxkj/xinjiang/zipdata:/zipdata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - qh_network
    stdin_open: true
    tty: true

networks:
  qh_network:
    driver: bridge